<?php
/**
 * @file
 * Install, update and uninstall functions for the premium_profile install profile.
 */

use Drupal\Core\Config\FileStorage;
use Drupal\Core\Entity\EntityStorageException;
use Drupal\Core\Utility\UpdateException;
use Drupal\imageapi_optimize\Entity\ImageAPIOptimizePipeline;
use Drupal\user\Entity\Role;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function premium_profile_install() {
  // First, do everything in standard profile.
  include_once DRUPAL_ROOT . '/core/profiles/standard/standard.install';
  standard_install();

  // Can add code in here to make nodes, terms, etc.
  $theme = getenv('PROJECT_NAME');

  \Drupal::service('theme_installer')->install([$theme]);

  \Drupal::configFactory()
    ->getEditable('system.theme')
    ->set('default', $theme)
    ->save();

  /** @var \Drupal\Core\Extension\ModuleInstaller $installer */
  $installer = \Drupal::service('module_installer');

  // Uninstall modules from the standard profile that we don't use
  $installer->uninstall(['quickedit', 'history']);

  // Install optional modules that are present
  $module_data = \Drupal::service('extension.list.module')->reset()->getList();
  $optional_modules = [
    'gtm',
    'cookiebot',
    'cookie_info',
    'content_hierarchy',
    'content_hierarchy_path',
    'content_hierarchy_breadcrumb',
    'ie_warning',
    'premium_articles',
    'premium_headless',
    'premium_search',
    'premium_maps'
  ];
  $installed_modules = [];
  foreach ($optional_modules as $module) {
    if (!empty($module_data[$module])) {
      $installed_modules[] = $module;
    }
  }
  if (!empty($installed_modules)) {
    $installer->install($installed_modules);
  }

  // Attach webp processor to image api optimize pipeline (optimize).
  $optimize = ImageAPIOptimizePipeline::load('optimize');
  if (!is_null($optimize)) {
    try {
      $optimize->addProcessor(['id' => 'webp_webp']);
      $optimize->save();
    }
    catch (EntityStorageException $e) {
      \Drupal::logger('premium_profile')->error($e->getMessage());
    }
  }

  drupal_flush_all_caches();

  node_access_rebuild();

  if (Drupal::moduleHandler()->moduleExists('role_delegation')) {
    $role_object = Role::load('webmaster');
    $role_object->grantPermission('assign editor role');
    $role_object->grantPermission('assign webmaster role');
    $role_object->save();
  }

  drupal_flush_all_caches();
}

/**
 * Install Premium Core and Promote Disable
 */
function premium_profile_update_9001(&$sandbox) {
  /** @var \Drupal\Core\Extension\ModuleInstaller $installer */
  $installer = \Drupal::service('module_installer');
  $module_data = \Drupal::service('extension.list.module')->reset()->getList();
  if (empty($module_data['premium_core'])) {
    throw new UpdateException('You need to add Premium Core to the project "composer require novicell/premium_core"');
  }
  $installer->install(['premium_core']);

  $config_names = ['block.block.premium_theme_pageheader', 'block.block.premium_theme_breadcrumbs'];
  foreach ($config_names as $config_name) {
    $config = \Drupal::configFactory()
      ->getEditable($config_name);
    $settings = $config->get('settings');
    $settings['provider'] = 'premium_core';
    $config->set('settings', $settings);
    $dependencies = $config->get('dependencies');
    $dependencies['module'] = ['premium_core'];
    $config->set('dependencies', $dependencies);
    $config->save();
  }

  if (\Drupal::moduleHandler()->moduleExists('promote_disable')) {
    $config_path = \Drupal::service('extension.list.profile')->getPath('premium_profile') . '/config/install';
    $config_source = new FileStorage($config_path);

    /** @var \Drupal\Core\Config\CachedStorage $config_storage */
    $config_storage = \Drupal::service('config.storage');
    $config_storage->write('promote_disable.settings', $config_source->read('promote_disable.settings'));
  }
}

/**
 * Prepare Styles migration
 */
function premium_profile_update_9002(&$sandbox) {
  /** @var \Drupal\Core\Extension\ModuleInstaller $installer */
  $installer = \Drupal::service('module_installer');
  $module_data = \Drupal::service('extension.list.module')->reset()->getList();
  if (empty($module_data['styles'])) {
    throw new UpdateException('You need to add Styles to the project "composer require novicell/styles"');
  }
  $installer->install(['styles']);

  /** @var \Drupal\styles\StylesManager $stylesManager */
  $stylesManager = \Drupal::service('styles.manager');
  $stylesManager->rebuild();
  if (empty($stylesManager->getCollection('color_theme'))) {
    throw new UpdateException('Color themes does not exist in Styles. Follow https://novicell.atlassian.net/wiki/spaces/TD/pages/3316777100/Premium+2.0+-+Premium+2.1');
  }
}
